apiVersion: v1
kind: Service
metadata:
  namespace: amqp-interconnect
  labels:
    app: router
  name: router
spec:
  ports:
  - name: "5672"
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: router
  type: ClusterIP
